### ISSUE TITLE
Support dynamic import

### ISSUE THREAD

**Issue by Halembek** [graphboss/aws-sam-webpack-plugin#25]
Currently this is not possible:

`const name:string = "my-module";
 const mod = await import("./path_to_my_modules" + name);`

Webpack chunks are generated outside lambda function directory.

**Comment by buggy** [comment]
After spending a few hours investigating this I've concluded that dynamic import's are incompatible with this plugin. It looks like you need to have one Webpack config per Lambda function. This won't change until Webpack allows us to configure a different output path for each entry point.

**Comment by msanandrea** [comment]
@buggy did you find any solution for his? Having same issue here...
