### ISSUE TITLE
bug: typescript definitions (index.d.ts) is empty

### ISSUE THREAD

**Issue by dmccaffery** [graphboss/aws-sam-webpack-plugin#28]
The `index.d.ts` included in the distribution of the node module is an empty object `{}` which means that the constructor cannot be called when writing a webpack config in typescript:

https://webpack.js.org/configuration/configuration-languages/#typescript

This may have to do with the way that the module export is defined.

**Comment by nickspiel** [comment]
I just came across the same. Thought I was taking crazy pills.

**Comment by buggy** [comment]
This will be fixed in 0.6.0
