### ISSUE TITLE
What is the CLI usage for this plugin?

### ISSUE THREAD

**Issue by iDVB** [graphboss/aws-sam-webpack-plugin#32]
Sorry, I'm not as familiar with SAM as I am with SLS and so not having the CLI usage leaves a bit to the imagination.

I have the plugin working and it generates a `.aws-sam` folder with the functions and a refactored template point to the new built function code.

At this point... Are we supposed to deploy like this...
```bash
sam package \
--template-file ./aws-sam/template.yaml \
--s3-bucket my-bucket \
--output-template-file ./aws-sam/packaged.yaml

sam deploy \
--template-file ./aws-sam/packaged.yaml \
--stack-name my-stack \
--capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND
```

**Comment by buggy** [comment]
@iDVB I'll update the docs for the next release. This plugin is strictly a replacement for the `sam build` step when using SAM CLI. The rest of the process remains the same and you should consult the SAM documentation. We used to run `sam package` but now simply use:

```sh
sam deploy \
  --template-file .aws-sam/build/template.yaml \
  --stack-name ${STACK_NAME} \
  --s3-bucket ${S3_BUCKET_NAME} \
  --capabilities CAPABILITY_NAMED_IAM \
  --parameter-overrides Param1=Val1 Param2=Val2 \
  --profile ${AWS_PROFILE} \
  --region ${AWS_REGION}
```

**Comment by iDVB** [comment]
Thanks @buggy super appreciate the plugin btw. I still find it surprising that this (or plugins ask in general) hasn’t been added to the Sam CLI yet.

FWIW, we’ve been using SLS for about 2yrs now and just not getting enough out of it. In the meantime, I’ve been doing a lot with raw CFN and dabbling with CDK. So I’m hoping the switch to SAM is possible and then on to CDK.
