### ISSUE TITLE
path is undefined error returned for javascript setup on macosx

### ISSUE THREAD

**Issue by spendres** [graphboss/aws-sam-webpack-plugin#34]
I had to add:

const path = require('path');
const fs = require('fs');

to the beginning of the webpack.config.js to get this plugin to work on macosx.

**Comment by metaskills** [comment]
Not just OS X, but these were lacking from the README.md examples in general.

**Comment by buggy** [comment]
Can you provide more info about your environments?
- Node version
- Webpack version
- Plugin version

I'm running this on a Mac without those and it's fine.

**Comment by spendres** [comment]
Hi Rich,

Thank you for writing this plugin!

Here's my setup:
Node version: v12.13.1
Webpack version: 4.41.6
Webpack-cli version: 3.3.11
Plugin version: 0.5.1
Running python 3.6.10 on zsh installed using pyenv

The webpack-cli throws the following error when I run:> npm run build

> babel-test/node_modules/webpack-cli/bin/cli.js:93
> throw err;
> ^
> ReferenceError: path is not defined


Is there a different sequence in your package.json than my dependency tree?


from my package.json:


"devDependencies": {

    "@babel/cli": "^7.8.4",

    "@babel/core": "^7.8.6",

    "@babel/plugin-proposal-class-properties": "^7.8.3",

    "@babel/plugin-transform-runtime": "^7.8.3",

    "@babel/preset-env": "^7.8.6",

    "@babel/preset-typescript": "^7.8.3",

    "babel-loader": "^8.0.6",

    "webpack": "^4.41.6",

    "webpack-cli": "^3.3.11"

  },

  "dependencies": {

    "@babel/runtime": "^7.8.4",

    "aws-sam-webpack-plugin": "^0.5.1",

    "aws-sdk": "^2.630.0",

    "source-map-support": "^0.5.16"

  },

  "scripts": {

    "build": "webpack-cli",

    "clean": "rimraf .aws-sam .vscode",

    "prewatch": "rimraf .aws-sam .vscode",

    "watch": "webpack-cli -w"

  }

Best,
Steve

**Comment by buggy** [comment]
I've been able to confirm that path is missing from the instructions. I'll correct that. I can't see the fs requirement.
