### ISSUE TITLE
async webpack wrap

### ISSUE THREAD

**Issue by spendres** [graphboss/aws-sam-webpack-plugin#35]
I have a very simple sam-init-generated async lambda:
exports.lambdaHandler = async (event, context) => {
    var response;
    try {
        // const ret = await axios(url);
        response = {
            'statusCode': 200,
            'body': JSON.stringify({
                message: 'hello world',
                // location: ret.data.trim()
            })
        }
    } catch (err) {
        console.log(err);
        return err;
    }

    return response
};

One issue I've noticed is how comments are handled. Running npm run build removes the comma before the comments in the object being converted to json. The web-pack processed version:
'statusCode': 200,
              'body': JSON.stringify({
                message: 'hello world' // location: ret.data.trim()

              })

When running the code Node returns:
Lambda returned empty body!
Invalid API Gateway Response Keys: {'errorType', 'errorMessage'} in {'errorType': 'TypeError', 'errorMessage': "Cannot set property 'wrap' of undefined"}

Another issue is that if I copy over the app.js in the build directory, the function returns 'hello world', so something is getting lost in the webpack process.

Steve

**Comment by spendres** [comment]
I get the same response from version .51 and .60 of the aws-sam-webpack-plugin

**Comment by buggy** [comment]
@spendres I'm 99% certain that your problem isn't caused by this plugin. Can you provide your Webpack config?
