### ISSUE TITLE
Cannnot debug TypeScript files

### ISSUE THREAD

**Issue by wojciech-dabrowski** [graphboss/aws-sam-webpack-plugin#36]
It seems that debugging TypeScript files is not possible.
My simplified project structure looks as follows:

```
│   package.json
│   template.yml
│   tsconfig.json
│   webpack.config.js
│
├───.aws-sam
│   └───build
│       │   template.yaml
│       │
│       └───MyFunction
│               app.js
│               app.js.map
│
├───.vscode
│       launch.json
│
└───src
    └───my-function
        │   app.ts
```
**tsconfig.json:**
```
{
  "compilerOptions": {
    "target": "es2020",
    "module": "commonjs",
    "allowJs": true,
    "checkJs": true,
    "sourceMap": true,
    "noImplicitAny": false,
    "strict": true,
    "esModuleInterop": true
  },
  "include": ["src/**/*.ts", "src/**/*.js"]
}
```
**launch.json**
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "MyFunction",
      "type": "node",
      "request": "attach",
      "address": "localhost",
      "port": 5858,
      "localRoot": "${workspaceRoot}/.aws-sam/build/MyFunction",
      "remoteRoot": "/var/task",
      "protocol": "inspector",
      "stopOnEntry": false,
      "outFiles": ["${workspaceRoot}/.aws-sam/build/MyFunction/app.js"],
      "sourceMaps": true,
      "sourceMapPathOverrides": {
        "webpack:///./~/*": "${workspaceRoot}/node_modules/*",
        "webpack:///./*": "${workspaceRoot}/src/my-function/*",
        "webpack:///*": "*"
      }
    }
  ]
}
```
In my **app.ts** file I have appropriate import `import "source-map-support/register";`
With this configuration, setting a breakpoint in **app.ts** results with nothing during debugging session. What can be an issue?

**Comment by buggy** [comment]
It looks like you're creating a custom `launch.json`. The plugin should create one for you with entries for every function. Can you try using the one the plugin creates?

**Comment by wojciech-dabrowski** [comment]
The plugin creates following `launch.json` file:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "MyFunction",
      "type": "node",
      "request": "attach",
      "address": "localhost",
      "port": 5858,
      "localRoot": "${workspaceRoot}/.aws-sam/build/MyFunction",
      "remoteRoot": "/var/task",
      "protocol": "inspector",
      "stopOnEntry": false,
      "outFiles": [
        "${workspaceRoot}/.aws-sam/build/MyFunction/app.js"
      ],
      "sourceMaps": true
    }
  ]
}
```
The only change in my version was adding this section:
```
      "sourceMapPathOverrides": {
        "webpack:///./~/*": "${workspaceRoot}/node_modules/*",
        "webpack:///./*": "${workspaceRoot}/src/my-function/*",
        "webpack:///*": "*"
      }
```
like you described in your blog post: https://www.goingserverless.com/blog/building-apps-with-sam-typescript-and-vscode-debugging

Anyway, in both cases I cannot debug TypeScript files. Btw, I am using Windows 10 if it matters.

**Comment by pedromdav** [comment]
Any news on this issue?
I'm having the same problem, can't debug locally with `sam invoke`.

**Comment by goldsam** [comment]
I'm also having trouble with this. @buggy Could you provide some clarification on how `source-map-support` should be incorporated?

**Comment by buggy** [comment]
You don't need `source-map-support` for local debugging with VS Code. I've updated the README to include instructions for using the VS Code debugger and source maps.

**Comment by guoliang** [comment]
@buggy 
I got the mentioned solution to work which is start SAM with 
> sam local invoke -d 5858

and then in VScode I start the debugger. However it only worked with JS files. For TS file it wouldn't stop at the break points

I got the following error when I try to debug lambas written in typescript 

> 2020-11-18T18:26:31.158Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'app'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","stack":["Runtime.ImportModuleError: Error: Cannot find module 'app'","Require stack:","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at _loadUserApp (/var/runtime/UserFunction.js:100:13)","    at Object.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:1135:14)","    at Object..js (internal/modules/cjs/loader.js:1158:10)","    at Module.load (internal/modules/cjs/loader.js:986:32)","    at Function._load (internal/modules/cjs/loader.js:879:14)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)","    at internal/main/run_main_module.js:17:47"]}
> START RequestId: f715a89a-4051-1595-6add-caff76c4d207 Version: $LATEST
> END RequestId: f715a89a-4051-1595-6add-caff76c4d207
> REPORT RequestId: f715a89a-4051-1595-6add-caff76c4d207	Init Duration: 4792.92 ms	Duration: 1.58 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 37 MB	
> 
> {"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'app'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js"}

**Comment by msanandrea** [comment]
It´s been a while, but if it's useful to anyone, I manage to make this working. The `sources` property wasn't mapping correctly my routes in the generated `app.js.map` . Changing the `devtoolModuleFilenameTemplate`  in the `webpack.config.js` **output**, to the right route, fix my debugging issue in VSCode.
