### ISSUE TITLE
Stop at the first line of index.js when debugging.

### ISSUE THREAD

**Issue by akycop** [graphboss/aws-sam-webpack-plugin#44]
When running the debug, it stops at the first line of index.js. Previously, it was running to the breakpoint.

The following process is used for debugging.
1. 'webpack watch'
2. 'sam local invoke -d 5858 testFunction'
3. Set to the target function from the VScode debug sidebar.
4. tell the F5 key to run the debug
5. stop on the first line of index.js.

![スクリーンショット 2020-10-06 11 39 40](https://user-images.githubusercontent.com/25409566/95152784-cd0d8100-07c8-11eb-9f90-602c9e9c9483.png)

Do you have any solutions for this?

**Comment by buggy** [comment]
I don't have a solution to it stopping on the first line of the bootstrap but if you press continue (again) it should go to the first breakpoint in your code.
