### ISSUE TITLE
Debugger doesn't stop at breakpoints in VScode

### ISSUE THREAD

**Issue by guoliang** [graphboss/aws-sam-webpack-plugin#46]
Hey, I followed few guides, all of them are basically like the one below.
https://github.com/vincedgy/aws-sam-webpack-typescript

and I also cloned the finished project to try out to debug
https://github.com/vincedgy/aws-sam-webpack-typescript/tree/master/demo

I have also tried to follow your instructions to run debugger for vscode/typescript.
None of which I got the debugger to stop at the breakpoints.

I can see in the console log that debugger got attached. It initially stop at the bootstrap file, but after that it just runs through without stopping on any breakpoints which I've  set.

> $ sam local invoke -d 5858 -e events/event.json HelloWorldFunction
> C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\chevron\renderer.py:73: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   if scope is 0:
> Invoking app.lambdaHandler (nodejs12.x)
> Skip pulling image and use local one: amazon/aws-sam-cli-emulation-image-nodejs12.x:rapid-1.9.0.
> 
> Mounting E:\Documents\Development\aws\aws-typescript\.aws-sam\build\HelloWorldFunction as /var/task:ro,delegated inside runtime container
> **Debugger attached.**
> ←[32mSTART RequestId: e0624f01-7b96-148c-27d4-d8c700e91db3 Version: $LATEST←[0m
> 2020-11-18T22:51:38.640Z        e0624f01-7b96-148c-27d4-d8c700e91db3    INFO    Hello World
> 2020-11-18T22:51:38.641Z        e0624f01-7b96-148c-27d4-d8c700e91db3    INFO    { statusCode: 200, body: '{"message":"hello world"}' }   
> ←[32mEND RequestId: e0624f01-7b96-148c-27d4-d8c700e91db3←[0m
> ←[32mREPORT RequestId: e0624f01-7b96-148c-27d4-d8c700e91db3     Init Duration: 355278.73 ms     Duration: 4.00 ms       Billed Duration: 
> 100 ms  Memory Size: 128 MB     Max Memory Used: 51 MB  ←[0m
> 
> {"statusCode":200,"body":"{\"message\":\"hello world\"}"}

I'm using
sam-cli 1.9.0
vscode 1.51

I'm not sure if I perhaps missing something. Maybe the following part where you mentioned source map support
https://github.com/graphboss/aws-sam-webpack-plugin#source-map-support

I'm not entirely sure how to set it, so I just applied it as global environment variable.

Any advice or suggestion would be really helpful.

**Comment by guoliang** [comment]
I got debugger to work for Javascript files with the following launch configuration

		{
			"type": "aws-sam",
			"request": "direct-invoke",
			"name": "sam-with-webpack-typescript",
			"invokeTarget": {
				"target": "code",
				"projectRoot": "sam-with-webpack-typescript",
				"lambdaHandler": "src/hello-world/app.lambdaHandler"
			},
			"lambda": {
				"runtime": "nodejs12.x",
				"payload": {},
				"environmentVariables": {}
			}
		},

Which also requires you to install `AWS Toolkit` first for VScode. However with that it still cannot recognize breakpoints in Typescript files.

**Comment by guoliang** [comment]
If someone else have issue with debugger doesn't work out of the box, I have found solution for it.

In my case, when running this on a Windows 10 machine.

One way is to use `debugger` in the code.
The other solution is in the generated launcher add `cwd` and write the path to the project folder

**Comment by dm430** [comment]
Im also having issues with this. I can' t seem to get debugging to work for the life of me.

**Comment by ryansonshine** [comment]
@dm430 for me it ended up being related to the function code itself; as soon as I dropped a console log statement it seemed to be able to debug from that point forward

**Comment by dm430** [comment]
@ryansonshine I wish that was the fix for me. Ive tried everything that I can thing of, but can not get vscode or chrome inspector to stop at break points set in the actual source files. I am able to step into the compiled code, but thats useless.

**Comment by AndrewZelaya** [comment]
I believe you have to run with the node environment variable set to development. Try running "NODE_ENV=development npm run-script watch" and then trying the debugger.

For me, if I don't set the env variable I get the same issues as you.

**Comment by buggy** [comment]
After some experimenting I think the problem is also related to the tsconfig.json. I've updated the README and have a working example at [aws-sam-webpack-demo](https://github.com/graphboss/aws-sam-webpack-demo).

**Comment by AndrewZelaya** [comment]
Circling back on this issue. Debugging breaks on the latest version of vscode (1.60.0). Verified with the demo. Version 1.59.1 works debugging works just fine.

**Comment by buggy** [comment]
@AndrewZelaya I've created a new issue for fixing debugging in VS Code 1.60.0. See #66
