### ISSUE TITLE
Support for DefinitionUri in AWS::Serverless: :StateMachine

### ISSUE THREAD

**Issue by lukasburns** [graphboss/aws-sam-webpack-plugin#51]
[AWS::Serverless::StateMachine](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html#sam-statemachine-definitionuri) supports a local file definition for its step functions, but it requires it uses sam package or sam build in. any workaround for this using aws-sam-webpack-plugin?

Thanks!

**Comment by Brymastr** [comment]
I've been using [`copy-webpack-plugin`](https://webpack.js.org/plugins/copy-webpack-plugin/) just to copy the state machine definition into the build directory.

In my template.yaml:
```
StateMachine:
  Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: path/to/StateMachineFile.asl.json
      ...
```

Then in my webpack.config.ts:
```typescript
import AwsSamPlugin from 'aws-sam-webpack-plugin';
import CopyWebpackPlugin from 'copy-webpack-plugin';
import { Configuration } from 'webpack';

const awsSamPlugin = new AwsSamPlugin();

const copyFiles = new CopyWebpackPlugin({
  patterns: [{ from: 'path/to/*', to: '.aws-sam/build/' }],
});

const config: Configuration = {
  plugins: [copyFiles, awsSamPlugin],
  ...
};
```

This sorta breaks the webpack method of doing things but it works. The alternative right now is to define the state machine inside your template.yaml but that can get pretty gross.

**Comment by lukasburns** [comment]
@Brymastr Im still getting the following error when the cloud formation change set is creating

> Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [KreditoJuridicalLoanEvaluation] is invalid. 'DefinitionUri' is not a valid S3 Uri of the form 's3://bucket/key' with optional versionId query parameter.

It seems its expecting an s3 url, how did you get past this?
Thanks!

**Comment by Brymastr** [comment]
@lukasburns A few questions:
1. Are you getting this error during the build step (webpack), `sam package`, `sam deploy`, or somewhere else?
1. Does your `.aws-sam/build` directory contain your statemachine file after the build step?

When everything is working correctly the `sam package/deploy` steps should upload your `.aws-sam/build` directory to AWS and convert code and statemachine templates to s3 URIs.

**Comment by lukasburns** [comment]
@Brymastr thanks! got it working
I was using `aws cloudformation package` instead of `sam package`,
Now its working beautifully!

Cheers! GL!

**Comment by buggy** [comment]
It looks like `sam build` is re-writing the file locations for the artifacts that `aws cloudformation package` can upload. I'll modify the plugin so that it does the same.

See https://docs.aws.amazon.com/cli/latest/reference/cloudformation/package.html

**Comment by MarsianMan** [comment]
When will this be released (or what version to use to get this fix)?

**Comment by buggy** [comment]
It will be in 0.10.0. You can track progress on that version at https://github.com/graphboss/aws-sam-webpack-plugin/milestone/7

**Comment by MarsianMan** [comment]
> It looks like `sam build` is re-writing the file locations for the artifacts that `aws cloudformation package` can upload. I'll modify the plugin so that it does the same.
> 
> See https://docs.aws.amazon.com/cli/latest/reference/cloudformation/package.html

For what it is worth, I think copying the state machines to the artifact directory makes more sense than rewriting the files to look at the src directory. That decision for `sam build` goes against most build paradigms and is clearly inconsistent with their own command😠 .
