### ISSUE TITLE
Generated template file should always be `template.yaml`

### ISSUE THREAD

**Issue by sschulze** [graphboss/aws-sam-webpack-plugin#52]
Hi,
I had a hard time tracking down a strange "module not found" error when starting my lambda with `sam local invoke` or using the deployed lambda. After some investigation I found, that SAM was bundling and starting/deploying the *.ts-files instead of the files in `.aws-sam/build/.../`.
After some further investigation I found that my template-file is named `template.yml` (which is valid for SAM and for the plugin). Prior to commit a7d3d5d8d (line 207) this was converted to `.aws-sam/build/template.y**a**ml` (similar to the behavior of sam-cli). In this commit the generated template use the same extension as the source one. Because of this it looks like sam-cli doesn't recognize it and uses the original one pointing to the source folder containing the TypeScript files.
As soon as I rename the generated file to template.yaml, everything works again...

**Comment by weltraumpirat** [comment]
Thank you so much for this post - I had the same issue and nearly went crazy trying to figure out why the ts file was being deployed, in spite of a correct template.yml in .aws-sam/build.

**Comment by linhx** [comment]
I was struggling with that.
Just found out by comparing the author's sample https://github.com/graphboss/aws-sam-webpack-demo with my project.
