### ISSUE TITLE
Possible Bug with compiling the webpack code

### ISSUE THREAD

**Issue by jgomes94** [graphboss/aws-sam-webpack-plugin#53]
Hi,

I've been having an issue for a few days and I can't figure it out . I am convinced that it might be due to webpack plugin but have no idea what can be causing it.

So I have the following code:
![image](https://user-images.githubusercontent.com/32710158/108508288-7e620e80-72b3-11eb-93d4-99ae9308fd31.png)

Now this code when I run it simply node app it works and I get the correct result: 
![image](https://user-images.githubusercontent.com/32710158/108508366-9c2f7380-72b3-11eb-822b-c81119fd92c0.png)

However, after compiling (via using the webpack-cli + sam local start-api) I always get 404 not found and I don't get the request I am expected to get via the data client. Somehow after the code runs through the webpack plugin it "breaks" it? 

I have the following configuration for webpack:
![image](https://user-images.githubusercontent.com/32710158/108508632-00eace00-72b4-11eb-87f9-6c95f275ded4.png)

Now I know the problem is not the database itself, because when I run it without the plugin it works.

Things that I've tried:
- I've used with Typescript, the answer was the same.
- Used several libs to access this database, Typeorm, data client api, native AWS RDS. With everytime the same issue.
-Used node v14 and node v12

I've been strugling with this problem for a few days so any help is much appreciated.

Thanks

**Comment by ryansonshine** [comment]
Hi @jgomes94 ,

Can you create a sample repo with all of the code? There could be a number of causes for this behavior.

**Comment by jgomes94** [comment]
Hi @ryansonshine , thank you for looking at this,

I've did as you suggested, I turned the optimization off and, yes, the data api client is in the dependencies. Unfortunately without success :(.

The code i'm using is this:
https://github.com/jgomes94/sam-node

for you to use it:
docker-compose up -d
npm i
npm run local-start

this will create you a single lambda that you can find in the localhost:3000/cards if you do a GET there you'll see the error.

The strange thing is, however, if you just navigate to /lambdas/create-card and do "node app" you'll see the code works and it prints the right information. (just make sure the file calls the function or it will not print anything you can do it by adding this.lambdaHandler() at the end of the file).

Again, thanks ryan much appreciated

**Comment by ryansonshine** [comment]
Hey @jgomes94 ,

Thanks for providing the sample. It appears you might have a misconfiguration in your `template.yaml`

Change
```yaml
CodeUri: lambdas/create-card/
```

to

```yaml
CodeUri: lambdas/create-card
```

without the trailing slash and let me know if that resolves your issue

**Comment by ryansonshine** [comment]
Also, that path is defined as a `POST` rather than a `GET` in the `template.yaml`

**Comment by jgomes94** [comment]
Thanks for the feedback @ryansonshine,

I've changed the codeUri, but unfortunately no success. The code runs, what fails the the data client with the query. I can see the logs that I print there, so I know that the lambda code is executed.

Did you download the code to your machine? It manage to query the database? or you also didn't get anything?

Yes sorry my fault i meant POST not GET.

**Comment by ryansonshine** [comment]
I see now, the issue you're experiencing is more related to how docker networking works between containers since AWS SAM is launching your lambda in a container of its own.

To solve this, you'll want to provide the `--docker-network` to the `sam local start-api` command as well as reference the endpoint by the hostname and path it would resolve as from within the docker network itself.

I've created a PR in your repository with the fix: https://github.com/jgomes94/sam-node/pull/1/files

**Comment by ryansonshine** [comment]
@buggy This can be closed as it relates to docker/aws sam rather than the plugin specifically.

**Comment by jgomes94** [comment]
I answered in the pull request @ryansonshine and it was totally it! Thank you very much!
