### ISSUE TITLE
Best way of building source code when other runtimes exist in the project

### ISSUE THREAD

**Issue by AndrewZelaya** [graphboss/aws-sam-webpack-plugin#55]
Wondering what exactly is the best way to use the plugin, and maintain the same file directory of "src/<lambda function>", but where not all functions are in the node runtime?

My project has a mix of lambda that are written in node, while others are written in python. Is there a better alternative than just building them as separate projects?

**Comment by buggy** [comment]
You need to build the Lambda as separate projects. One of the early decisions was to optimize the experience for Node developers even if that meant not supporting other runtimes.
