### ISSUE TITLE
Improve webpack build performance

### ISSUE THREAD

**Issue by MarsianMan** [graphboss/aws-sam-webpack-plugin#56]
Right now filename seems very coupled to the entry point template. I would like to use conventional webpack caching/build optimizations but not sure how to integrate into this plugin without breaking. Any help would be appreciated

##### Webpack guides
https://webpack.js.org/guides/caching/
https://webpack.js.org/guides/build-performance/

**Comment by MarsianMan** [comment]
It turns out, this also affects stack traces when errors are thrown in lambdas making it much more difficult to figure out errors because everything boils down to some line and column in `app.js` and that is even with source maps support in AWS.

**Comment by buggy** [comment]
@MarsianMan I've been looking at the chunk loading for the dynamic import issue. Unfortunately it's incompatible with the way the plugin currently works as Webpack only supports one output path.
