### ISSUE TITLE
Support for Node 14

### ISSUE THREAD

**Issue by gustavjorlov** [graphboss/aws-sam-webpack-plugin#60]
Does the plugin _not_ support Node 14, or is it just not tested yet?

**Comment by alonefox** [comment]
plugin nice support node 14. 
I am using nice it.

> Does the plugin _not_ support Node 14, or is it just not tested yet?

**Comment by gustavjorlov** [comment]
Maybe it's just not added to the README then? I can't really see why it wouldn't work, but there are always details that might differ I guess.

**Comment by alonefox** [comment]
> Maybe it's just not added to the README then? I can't really see why it wouldn't work, but there are always details that might differ I guess.

I did make PR. And I think @buggy will be approve it.

All depends of node version contains into your webpack config. Plugin do not depends of node version.
