### ISSUE TITLE
build.toml

### ISSUE THREAD

**Issue by sezeresim** [graphboss/aws-sam-webpack-plugin#67]
Hello, i tried this library with build.I have a question about the build.toml file.When i was building with sam-cli .aws-sam include build.toml file but i cant see with webpack plugin.Is it critical or not ?

**Comment by buggy** [comment]
The build.toml is used for storing sam-cli settings. It's not generated or used by this webpack plugin.

**Comment by sezeresim** [comment]
> The build.toml is used for storing sam-cli settings. It's not generated or used by this webpack plugin.

Yes i know,just i am wondering is it crical for build process?

**Comment by buggy** [comment]
It's got nothing to do with the build process. It's for deploymnets
