### ISSUE TITLE
Files generated outside .aws-sam folder

### ISSUE THREAD

**Issue by msanandrea** [graphboss/aws-sam-webpack-plugin#95]
I'm my project I'm using `@aws-sdk/client-cloudwatch-logs` and `@aws-sdk/client-ssm`, both as `devDependencies` as they're already included in the AWS Lambda environment. Even though webpack compiles and packages correctly my `index.js` file, I'm seeing all these auto-generated files outside my `.aws-sam` folder. How can I fix this and why are being generated?

![plugin files](https://github.com/user-attachments/assets/295fd574-aaca-4eb0-aa4d-7b7514cf81cb)

**Comment by msanandrea** [comment]
@buggy ?

**Comment by buggy** [comment]
Now that SAM has official support for Typescript I'm recommending people use it.

I'm not in a position to provide support beyond adding new runtimes to keep the project alive while people migrate.
